# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.2.0
        hooks:
            -   id: trailing-whitespace
            -   id: mixed-line-ending
            -   id: check-yaml
            -   id: check-added-large-files
            -   id: check-case-conflict
            -   id: check-executables-have-shebangs
            -   id: check-shebang-scripts-are-executable
            -   id: check-symlinks
            -   id: destroyed-symlinks
            -   id: debug-statements

    -   repo: https://github.com/psf/black
        rev: 22.3.0
        hooks:
            -   id: black

    - repo: https://github.com/PyCQA/bandit
      rev: '1.7.4'
      hooks:
          - id: bandit
            args: ["-c", "bandit.yml"]

    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: v0.0.139
      hooks:
          - id: ruff
